
import { jsPDF } from "jspdf";
import autoTable, { UserOptions } from "jspdf-autotable";
import { Site, FeasibilityScenario, CostCategory, SiteDNA, MonthlyFlow, RevenueItem, LineItem, GstTreatment } from "../types";
import { FinanceEngine, ItemisedCashflow } from "./financeEngine";
import { SensitivityService } from "./sensitivityService";

// --- THEME CONSTANTS ---
const THEME = {
  primary: "#1e293b", // Slate 800 (Feastudy is Black/Dark Grey)
  secondary: "#334155", // Slate 700
  accent: "#4f46e5", // Indigo (Branding)
  headerFill: "#e2e8f0", // Slate 200 (The "Gray Bar" for headers)
  text: "#0f172a", // Slate 900
  line: "#cbd5e1" // Slate 300
};

// --- HELPERS ---
const formatCurrency = (val: number, decimals = 0) => {
  if (val === 0) return "-";
  const absVal = Math.abs(val).toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
  return val < 0 ? `(${absVal})` : `${absVal}`;
};

const formatPct = (val: number) => `${val.toFixed(2)}%`;

// --- TYPES FOR RENDERER ---
type RowType = 'header' | 'item' | 'subtotal' | 'total' | 'spacer';

interface ReportRow {
  type: RowType;
  label: string;
  values: (string | number)[];
  indent?: number; // 0, 1, 2
  bold?: boolean;
  fill?: boolean;
}

export class PdfService {
  private doc: jsPDF;
  private pageWidth: number;
  private pageHeight: number;
  private currentY: number = 0;

  constructor() {
    this.doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    this.pageWidth = this.doc.internal.pageSize.width;
    this.pageHeight = this.doc.internal.pageSize.height;
  }

  // --- PUBLIC ORCHESTRATOR ---
  public static async generateBoardReport(
    site: Site,
    scenario: FeasibilityScenario,
    stats: any,
    cashflow: MonthlyFlow[],
    siteDNA: SiteDNA
  ) {
    const service = new PdfService();
    const itemisedData = FinanceEngine.generateItemisedCashflowData(scenario, siteDNA);
    await service.buildDocument(site, scenario, stats, cashflow, siteDNA, itemisedData);
  }

  private async buildDocument(
    site: Site,
    scenario: FeasibilityScenario,
    stats: any,
    cashflow: MonthlyFlow[],
    siteDNA: SiteDNA,
    itemisedData: ItemisedCashflow
  ) {
    // 1. Executive Summary (Portrait)
    this.addExecutiveSummary(site, scenario, stats);
    this.addFooter(1, site.name);

    // 2. Valuer's P&L (Portrait - Detailed 3-Column)
    this.doc.addPage();
    this.addValuersPnL(scenario, siteDNA, stats);
    this.addFooter(2, site.name);

    // 3. Itemised Cashflow (Landscape - 12 Month Chunks)
    this.addItemisedCashflow(itemisedData, site.name, 3);

    // Save
    this.doc.save(`Feastudy_Report_${site.code}.pdf`);
  }

  // --- HEADER & FOOTER ---
  private addHeader(title: string, subtitle: string, landscape = false) {
    const width = landscape ? this.doc.internal.pageSize.height : this.pageWidth; // Swap dimensions logic for header line if landscape
    const effectiveWidth = landscape ? 297 : 210;

    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(14);
    this.doc.setTextColor(THEME.text);
    this.doc.text("PROPERTY DEVELOPMENT FEASIBILITY STUDY", effectiveWidth / 2, 15, { align: "center" });
    
    this.doc.setDrawColor(0);
    this.doc.setLineWidth(0.5);
    this.doc.line(10, 18, effectiveWidth - 10, 18);

    this.doc.setFontSize(10);
    this.doc.text(`Development:`, 10, 25);
    this.doc.setFont("helvetica", "normal");
    this.doc.text(title, 40, 25);

    this.doc.setFont("helvetica", "bold");
    this.doc.text(`Description:`, 10, 30);
    this.doc.setFont("helvetica", "normal");
    this.doc.text(subtitle, 40, 30);

    this.doc.line(10, 35, effectiveWidth - 10, 35);
    this.currentY = 45;
  }

  private addFooter(pageNumber: number, projectName: string) {
    const totalPages = this.doc.getNumberOfPages();
    const width = this.doc.internal.pageSize.width;
    const height = this.doc.internal.pageSize.height;

    this.doc.setFontSize(8);
    this.doc.setFont("helvetica", "italic");
    this.doc.setTextColor(100);
    
    this.doc.line(10, height - 15, width - 10, height - 15);
    this.doc.text("Generated by DevFeas Pro | Professional Edition", 10, height - 10);
    this.doc.text(`Page ${pageNumber}`, width - 10, height - 10, { align: "right" });
  }

  // --- PAGE 1: EXECUTIVE SUMMARY ---
  private addExecutiveSummary(site: Site, scenario: FeasibilityScenario, stats: any) {
    this.addHeader(scenario.name, site.name);
    
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(12);
    this.doc.text("Executive Dashboard", 10, this.currentY);
    this.currentY += 10;

    // KPI Grid
    const kpis = [
      ["Net Profit", formatCurrency(stats.profit)],
      ["Dev Margin", formatPct(stats.margin)],
      ["Equity IRR", formatPct(stats.irr)],
      ["Peak Debt", formatCurrency(stats.peakTotalDebt)],
      ["Total Cost", formatCurrency(stats.totalOut)],
      ["Duration", `${scenario.settings.durationMonths} Months`]
    ];

    autoTable(this.doc, {
      startY: this.currentY,
      head: [['Metric', 'Value', 'Metric', 'Value']],
      body: [
        [kpis[0][0], kpis[0][1], kpis[1][0], kpis[1][1]],
        [kpis[2][0], kpis[2][1], kpis[3][0], kpis[3][1]],
        [kpis[4][0], kpis[4][1], kpis[5][0], kpis[5][1]],
      ],
      theme: 'grid',
      headStyles: { fillColor: THEME.primary, textColor: 255, fontStyle: 'bold' },
      styles: { font: "courier", fontSize: 10, cellPadding: 4 },
      columnStyles: {
        0: { font: "helvetica", fontStyle: "bold", fillColor: 245 },
        2: { font: "helvetica", fontStyle: "bold", fillColor: 245 }
      }
    });

    this.currentY = (this.doc as any).lastAutoTable.finalY + 15;

    // Narrative
    this.doc.setFont("helvetica", "bold");
    this.doc.text("Project Commentary", 10, this.currentY);
    this.currentY += 6;
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10);
    const desc = scenario.settings.description || "No description provided.";
    const splitDesc = this.doc.splitTextToSize(desc, 190);
    this.doc.text(splitDesc, 10, this.currentY);
  }

  // --- PAGE 2: VALUER'S P&L (The Feastudy Style) ---
  private addValuersPnL(scenario: FeasibilityScenario, siteDNA: SiteDNA, stats: any) {
    this.addHeader(scenario.name, "Itemised Profit & Loss (Valuer's Style)");

    // Pre-Process Data Structure for 3-Column Table
    // Col 1: Description (Indented)
    // Col 2: Inner Amount (Individual Items)
    // Col 3: Outer Amount (Subtotals/Totals)

    const rows: any[] = [];
    const pushRow = (desc: string, inner: string | null, outer: string | null, style: 'header'|'item'|'total'|'spacer' = 'item') => {
        rows.push({ desc, inner, outer, style });
    };

    const reportStats = FinanceEngine.calculateReportStats(scenario, siteDNA);

    // 1. REVENUE SECTION
    pushRow("INCOME", null, null, 'header');
    pushRow("Gross Sales Revenue", formatCurrency(reportStats.totalRevenueGross), null);
    pushRow("Less: GST Liability", formatCurrency(reportStats.gstCollected * -1), null);
    pushRow("NET REALISATION", null, formatCurrency(reportStats.netRealisation), 'total');
    pushRow("", null, null, 'spacer');

    // 2. COSTS SECTION
    pushRow("LESS DEVELOPMENT COSTS", null, null, 'header');

    // Helper to process a category
    const processCategory = (catName: string, catId: CostCategory) => {
        const items = scenario.costs.filter(c => c.category === catId);
        if (items.length === 0) return;

        // Calculate Category Total
        const constructionSum = scenario.costs.filter(c => c.category === CostCategory.CONSTRUCTION).reduce((a,b)=>a+b.amount,0);
        const revenueSum = reportStats.totalRevenueGross;
        const total = items.reduce((sum, item) => sum + FinanceEngine.calculateLineItemTotal(item, scenario.settings, siteDNA, constructionSum, revenueSum), 0);

        pushRow(catName, null, null, 'header');
        items.forEach(item => {
            const val = FinanceEngine.calculateLineItemTotal(item, scenario.settings, siteDNA, constructionSum, revenueSum);
            pushRow(item.description, formatCurrency(val), null);
        });
        pushRow(`Total ${catName}`, null, formatCurrency(total), 'total');
        pushRow("", null, null, 'spacer');
    };

    processCategory("Acquisition Costs", CostCategory.LAND);
    processCategory("Construction Costs", CostCategory.CONSTRUCTION);
    processCategory("Consultant Fees", CostCategory.CONSULTANTS);
    processCategory("Statutory & Authorities", CostCategory.STATUTORY);
    processCategory("Selling & Marketing", CostCategory.SELLING);
    processCategory("Miscellaneous", CostCategory.MISCELLANEOUS);

    // Finance
    pushRow("Finance Costs", null, null, 'header');
    pushRow("Interest & Line Fees", null, formatCurrency(stats.interestTotal), 'total');
    
    // Bottom Line
    pushRow("", null, null, 'spacer');
    pushRow("TOTAL DEVELOPMENT COST", null, formatCurrency(stats.totalOut), 'header');
    pushRow("", null, null, 'spacer');
    
    // Profit
    pushRow("NET DEVELOPMENT PROFIT", null, formatCurrency(stats.profit), 'header');
    pushRow("DEVELOPMENT MARGIN", null, formatPct(stats.margin), 'total');

    // RENDER TABLE
    autoTable(this.doc, {
        startY: this.currentY,
        head: [['Description', 'Amount', 'Subtotal']],
        body: rows.map(r => [r.desc, r.inner, r.outer]),
        theme: 'plain',
        styles: { fontSize: 9, cellPadding: 2, font: "helvetica" },
        columnStyles: {
            0: { cellWidth: 110 },
            1: { cellWidth: 40, halign: 'right', font: "courier" },
            2: { cellWidth: 40, halign: 'right', font: "courier", fontStyle: 'bold' }
        },
        didParseCell: (data) => {
            const rowIdx = data.row.index;
            const style = rows[rowIdx].style;

            if (data.section === 'head') {
                data.cell.styles.fillColor = THEME.primary;
                data.cell.styles.textColor = 255;
            }

            if (data.section === 'body') {
                if (style === 'header') {
                    if (data.column.index === 0) data.cell.styles.fontStyle = 'bold';
                    data.cell.styles.fillColor = THEME.headerFill;
                } else if (style === 'item') {
                    if (data.column.index === 0) data.cell.styles.cellPadding = { top: 2, bottom: 2, left: 8, right: 2 };
                } else if (style === 'total') {
                    data.cell.styles.fontStyle = 'bold';
                    if (data.column.index === 2) data.cell.styles.lineWidth = { top: 0.1, bottom: 0, left: 0, right: 0 };
                }
            }
        }
    });
  }

  // --- PAGE 3: ITEMISED CASHFLOW (Chunked) ---
  private addItemisedCashflow(data: ItemisedCashflow, projectName: string, startPageNum: number) {
    const monthsPerPage = 12; // Strictly 12 months for readable A4 landscape
    const totalMonths = data.headers.length;
    const totalPagesHorizontal = Math.ceil(totalMonths / monthsPerPage);
    let currentPageNum = startPageNum;

    for (let i = 0; i < totalPagesHorizontal; i++) {
        this.doc.addPage("a4", "landscape");
        const pageWidth = 297;
        
        // Custom Header for Cashflow Pages
        this.doc.setFont("helvetica", "bold");
        this.doc.setFontSize(14);
        this.doc.text("ITEMISED COST CASHFLOW", pageWidth / 2, 15, { align: "center" });
        this.doc.setFontSize(10);
        this.doc.setFont("helvetica", "normal");
        const startM = i * monthsPerPage;
        const endM = Math.min((i + 1) * monthsPerPage, totalMonths);
        this.doc.text(`Period: Month ${startM + 1} to Month ${endM}`, pageWidth / 2, 20, { align: "center" });
        this.currentY = 30;

        // Slice Data
        const currentHeaders = data.headers.slice(startM, endM);
        
        // Build Pre-Processed Rows for AutoTable
        const tableBody: any[] = [];
        
        // Helper to push stylized rows
        const addHeaderRow = (label: string) => {
            tableBody.push({ 0: label, type: 'header' });
        };
        const addItemRow = (label: string, values: number[]) => {
            // Filter out empty rows? No, bankers want to see zeros if the item exists.
            const rowObj: any = { 0: label, type: 'item' };
            values.forEach((v, idx) => {
                rowObj[idx + 1] = v === 0 ? '-' : Math.round(v).toLocaleString();
            });
            // Total Column (Only on last page? Or running total? Feastudy usually sums the visible range or has a total column at very end)
            // We will add a "Page Total" or just keep it simple.
            // Feastudy screenshot shows "Subtotals" column.
            const rowSum = values.reduce((a,b) => a+b, 0);
            rowObj[currentHeaders.length + 1] = formatCurrency(rowSum);
            
            tableBody.push(rowObj);
        };

        // Iterate Categories
        data.categories.forEach(cat => {
            // Only add category if it has non-zero total in this chunk OR generally not empty?
            // Cleanest report removes zero-sum lines for the period.
            const catSliceTotal = cat.monthlyTotals.slice(startM, endM).reduce((a,b)=>a+b, 0);
            
            // Allow printing empty categories if they are major ones (Construction), otherwise skip
            if (catSliceTotal === 0 && cat.total === 0) return;

            addHeaderRow(cat.name.toUpperCase());
            
            cat.rows.forEach(row => {
                const slice = row.values.slice(startM, endM);
                const sliceTotal = slice.reduce((a,b) => a+b, 0);
                if (row.total > 0 || sliceTotal > 0) {
                    addItemRow(row.label, slice);
                }
            });

            // Category Subtotal Row
            const catRow: any = { 0: `Total ${cat.name}`, type: 'subtotal' };
            cat.monthlyTotals.slice(startM, endM).forEach((v, idx) => {
                catRow[idx + 1] = formatCurrency(v);
            });
            catRow[currentHeaders.length + 1] = formatCurrency(catSliceTotal);
            tableBody.push(catRow);
        });

        // Net Cashflow Row
        const netSlice = data.netCashflow.slice(startM, endM);
        const netRow: any = { 0: "NET MONTHLY FLOW", type: 'net' };
        netSlice.forEach((v, idx) => netRow[idx + 1] = formatCurrency(v));
        netRow[currentHeaders.length + 1] = formatCurrency(netSlice.reduce((a,b)=>a+b, 0));
        tableBody.push(netRow);

        // Columns
        const columns = [
            { header: 'Item', dataKey: '0' },
            ...currentHeaders.map((h, idx) => ({ header: h, dataKey: (idx + 1).toString() })),
            { header: 'Period Total', dataKey: (currentHeaders.length + 1).toString() }
        ];

        // Render
        autoTable(this.doc, {
            startY: this.currentY,
            columns: columns,
            body: tableBody,
            theme: 'plain',
            styles: { fontSize: 7, cellPadding: 1.5, font: "courier", halign: 'right' },
            columnStyles: { 
                0: { halign: 'left', cellWidth: 50, font: "helvetica" } // Description Col
            },
            headStyles: { fillColor: THEME.primary, textColor: 255, halign: 'center', font: "helvetica", fontStyle: "bold" },
            didParseCell: (data) => {
                if (data.section === 'body') {
                    const type = data.row.raw.type;
                    
                    if (type === 'header') {
                        data.cell.styles.font = "helvetica";
                        data.cell.styles.fontStyle = 'bold';
                        data.cell.styles.fillColor = THEME.headerFill;
                        data.cell.styles.halign = 'left';
                    } 
                    else if (type === 'item') {
                        if (data.column.index === 0) {
                            data.cell.styles.cellPadding = { top: 1, bottom: 1, left: 6, right: 2 }; // Indent
                        }
                    }
                    else if (type === 'subtotal') {
                        data.cell.styles.fontStyle = 'bold';
                        data.cell.styles.fillColor = 250; // Very light grey
                        if (data.column.index === 0) data.cell.styles.halign = 'right'; // Align "Total X" to right of label col
                        // Top border for sums
                        data.cell.styles.lineWidth = { top: 0.1, bottom: 0, left: 0, right: 0 };
                    }
                    else if (type === 'net') {
                        data.cell.styles.fontStyle = 'bold';
                        data.cell.styles.fillColor = THEME.primary;
                        data.cell.styles.textColor = 255;
                    }
                }
            }
        });

        // Add Footer to Landscape Page
        const footerText = `Generated by DevFeas Pro | ${projectName} | Page ${currentPageNum} (Months ${startM+1}-${endM})`;
        this.doc.setFontSize(8);
        this.doc.setTextColor(100);
        this.doc.text(footerText, 10, 200); // 210 is height, so 200 is near bottom
        
        currentPageNum++;
    }
  }

  // --- UTILS ---
  private renderPlaceholderImage(x: number, y: number, w: number, h: number) {
    this.doc.setFillColor(240);
    this.doc.rect(x, y, w, h, "F");
    this.doc.setTextColor(150);
    this.doc.setFontSize(10);
    this.doc.text("Map / Visual Unavailable", x + w/2, y + h/2, { align: "center" });
  }
}
